void transmit_data() {
  Serial.print(roll, 2);
  Serial.print("\t");
  Serial.print(pitch, 2);
  Serial.print("\t");
  Serial.print(yaw, 2);
  Serial.println("\t"); 
  // Serial.print(throttle);
  // Serial.print("\t"); 
  // Serial.print(pid_roll, 2);
  // Serial.print("\t"); 
  // Serial.print(pid_pitch, 2);
  // Serial.print("\t"); 
  // Serial.print(pid_yaw, 2);
  // Serial.print("\t"); 
  // Serial.print(esc_1);
  // Serial.print("\t");
  // Serial.print(esc_2);
  // Serial.print("\t");
  // Serial.print(esc_3);
  // Serial.print("\t");
  // Serial.print(esc_4);
  // Serial.print("\t");
  // Serial.println(error);
  // Serial.print("\t");
  // Serial.print(channel_1);
  // Serial.print("\t");
  // Serial.print(channel_2);
  // Serial.print("\t");
  // Serial.print(channel_3);
  // Serial.print("\t");
  // Serial.println(channel_4);
}